name: "JSRunner"
on:
   workflow_dispatch:
      inputs:
         api_variables:
            description: "api_variables"
            required: false
            default: ""
         api_variables_1:
            description: "api_variables_1"
            required: false
            default: ""
         api_variables_2:
            description: "api_variables_2"
            required: false
            default: ""
         api_variables_3:
            description: "api_variables_3"
            required: false
            default: ""
         api_variables_4:
            description: "api_variables_4"
            required: false
            default: ""
         api_variables_5:
            description: "api_variables_5"
            required: false
            default: ""
jobs:
   JSRunner:
      runs-on: ubuntu-latest
      name: JSRunner
      env:
         toJSON_github: ${{ toJSON(github) }}
         toJSON_secrets: ${{ toJSON(secrets) }}
      steps:
         # - name: Checkout
         #   uses: actions/checkout@v2
         # - name: Setup Rclone
         #   uses: AnimMouse/setup-rclone@v1
         - uses: actions/checkout@v3
           with:
              # Repository name with owner. For example, actions/checkout
              # Default: ${{ github.repository }}
              repository: "o-workflows-00/first-00-code"
              token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
              # The branch, tag or SHA to checkout. When checking out the repository that
              # triggered a workflow, this defaults to the reference or SHA for that event.
              # Otherwise, uses the default branch.
              ref: "main"
         - name: Run node jsrunner.js - 1
           timeout-minutes: 1 # Times out after 1 minute
           run: node jsrunner.js
           continue-on-error: true
         - name: Run node jsrunner.js - 2
           timeout-minutes: 1 # Times out after 1 minute
           run: node jsrunner.js
           continue-on-error: true
         - name: Run node jsrunner.js - 3
           timeout-minutes: 1 # Times out after 1 minute
           run: node jsrunner.js
           continue-on-error: true
         - name: Run node jsrunner.js - 4
           timeout-minutes: 1 # Times out after 1 minute
           run: node jsrunner.js
           continue-on-error: true
         - name: Run node jsrunner.js - 5
           timeout-minutes: 1 # Times out after 1 minute
           run: node jsrunner.js
           continue-on-error: true
