name: "JSRunner"
on:
   workflow_dispatch:
      inputs:
         api_variables:
            description: "api_variables"
            required: false
            default: ""
         api_variables_1:
            description: "api_variables_1"
            required: false
            default: ""
         api_variables_2:
            description: "api_variables_2"
            required: false
            default: ""
         api_variables_3:
            description: "api_variables_3"
            required: false
            default: ""
         api_variables_4:
            description: "api_variables_4"
            required: false
            default: ""
         api_variables_5:
            description: "api_variables_5"
            required: false
            default: ""
jobs:
   JSRunner:
      runs-on: ubuntu-latest
      name: JSRunner
      env:
         toJSON_github: ${{ toJSON(github) }}
         toJSON_secrets: ${{ toJSON(secrets) }}
      steps:
         # - name: Checkout
         #   uses: actions/checkout@v2
         # - name: Setup Rclone
         #   uses: AnimMouse/setup-rclone@v1
         - uses: actions/checkout@v3 #docs: https://github.com/actions/checkout
           with:
              repository: "o-workflows-00/first-00-code"
              token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
              ref: "main"
         - name: Install ngrok sudo tar xvzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
           run: |
              sudo tar xvzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
           shell: bash
         - name: Run node app.js --oforever=true -1
           #   https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
           #   Job execution time - Each job in a workflow can run for up to 6 hours of execution time.
           #                      If a job reaches this limit, the job is terminated and fails to complete.
           #   Workflow run time - Each workflow run is limited to 35 days.
           #                      If a workflow run reaches this limit, the workflow run is cancelled.
           #                      This period includes execution duration, and time spent on waiting and approval
         #   timeout-minutes: 5 # Times out after 2 minute
         #   run: node app.js --oforever=true
         #   continue-on-error: true
         # - name: Run node alive.js - 2
         #   timeout-minutes: 360 # Times out after 2 minute
         #   run: node alive.js
         #   continue-on-error: true
         # - name: Run node alive.js - 3
         #   timeout-minutes: 360 # Times out after 2 minute
         #   run: node alive.js
         #   continue-on-error: true
         # - name: Run node alive.js - 4
         #   timeout-minutes: 360 # Times out after 2 minute
         #   run: node alive.js
         #   continue-on-error: true
         # - name: Run node alive.js - 5
         #   timeout-minutes: 360 # Times out after 2 minute
         #   run: node alive.js
         #   continue-on-error: true
