name: "JSRunner"
on:
   workflow_dispatch:
      inputs:
         api_variables:
            description: "api_variables"
            required: false
            default: ""
         api_variables_1:
            description: "api_variables_1"
            required: false
            default: ""
         api_variables_2:
            description: "api_variables_2"
            required: false
            default: ""
         api_variables_3:
            description: "api_variables_3"
            required: false
            default: ""
         api_variables_4:
            description: "api_variables_4"
            required: false
            default: ""
         api_variables_5:
            description: "api_variables_5"
            required: false
            default: ""
jobs:
   JSRunner:
      runs-on: ubuntu-latest
      name: JSRunner
      env:
         toJSON_github: ${{ toJSON(github) }}
         toJSON_secrets: ${{ toJSON(secrets) }}
      steps:
         # - name: Checkout
         #   uses: actions/checkout@v2
         # - name: Setup Rclone
         #   uses: AnimMouse/setup-rclone@v1
         - uses: actions/checkout@v3 #docs: https://github.com/actions/checkout
           with:
              repository: "o-workflows-00/first-00-code"
              token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
              ref: "main"
         - name: Start ngrok
           run: |
              ls
              sudo tar xvzf ./ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin
           shell: bash
         - name: Run node app.js - 1
           timeout-minutes: 3 # Times out after 3 minute
           run: node app.js --oforever=true
           continue-on-error: true
         - name: Run node app.js - 2
           timeout-minutes: 3 # Times out after 3 minute
           run: node app.js --oforever=true
           continue-on-error: true
         - name: Run node app.js - 3
           timeout-minutes: 3 # Times out after 3 minute
           run: node app.js --oforever=true
           continue-on-error: true
         - name: Run node app.js - 4
           timeout-minutes: 3 # Times out after 3 minute
           run: node app.js --oforever=true
           continue-on-error: true
         - name: Run node app.js - 5
           timeout-minutes: 3 # Times out after 3 minute
           run: node app.js --oforever=true
           continue-on-error: true
